/**
 * @jest-environment node
 *
 * H4 (fix-2.2.0-blockers) — `dist/bundle-sizes.json` is generated by
 * `generate:bundle-sizes`, but no glob in `package.json`'s `files` array
 * matched a `.json` under `dist/`, so `npm pack` silently dropped it from
 * every published tarball. `src/cli/index.cjs` reads exactly
 * `node_modules/minder-data-provider/dist/bundle-sizes.json` — the path
 * README.md tells users to invoke via `npx minder doctor --bundle` — so
 * every real install had a broken command. That glob fix (`dist/**\/*.json`
 * in `files`) is still correct and is asserted below.
 *
 * REGRESSION (this program, FIX-B) — the glob was fine, but the file it
 * matches was regenerated by `generate:bundle-sizes` was only ever wired to
 * `prepublishOnly`. npm's lifecycle only runs `prepublishOnly` for
 * `npm publish` — it does NOT run for a bare `npm pack`. This repo's release
 * process never runs `npm publish` from CI or from an agent (owner-run,
 * manual step — see RELEASING.md); every "packed tarball" used for
 * validation in this repo is produced with `npm pack`. So the file was
 * generated for a code path (`npm publish`) that never actually executes
 * here, and omitted from every artifact that does (`npm pack`).
 *
 * Confirmed by direct repro (see task report): deleting `dist/bundle-sizes.json`
 * and running a REAL `npm pack` (no `--dry-run`, which skips lifecycle
 * scripts entirely and therefore cannot exercise this bug at all) produced a
 * tarball containing only `package/package.json` under `*.json` — the file
 * never came back, because nothing in the `npm pack` lifecycle regenerates it.
 *
 * FIX: `prepack` — the one npm lifecycle script that fires for BOTH
 * `npm pack` and `npm publish` — now runs `generate:bundle-sizes`. This is
 * the single choke point every packing path goes through; `prepublishOnly`
 * keeps its own call too (harmless — generation is idempotent) so a bare
 * `npm publish` still gets a guaranteed-fresh file before its full gate runs.
 *
 * Test posture: this suite proves the fix with a REAL (non-dry-run) `npm
 * pack`, because `--dry-run` never executes lifecycle scripts and so cannot
 * distinguish "the file happens to exist already" from "packing regenerates
 * it" — which is exactly the distinction that let this regress once already.
 * Guarded with a hard `existsSync(dist)` throw, not a skip — same posture as
 * every other file in this directory (see cjs-no-esm-dynamic-import.test.ts's
 * header for why).
 */
import { execFileSync } from 'node:child_process';
import {
  existsSync,
  mkdtempSync,
  readdirSync,
  readFileSync,
  rmSync,
  unlinkSync,
  writeFileSync,
} from 'node:fs';
import { tmpdir } from 'node:os';
import { join, resolve } from 'node:path';

const root = resolve(__dirname, '../..');
const distDir = resolve(root, 'dist');
const bundleSizesPath = resolve(distDir, 'bundle-sizes.json');

if (!existsSync(distDir)) {
  throw new Error(
    `tests/packaging expects dist/ to exist (found nothing at ${distDir}). ` +
      'This suite must run AFTER `npm run build`, never standalone.',
  );
}

// Regenerates dist/bundle-sizes.json directly (mirrors the `generate:bundle-sizes`
// npm script) — used only as a post-test safety net so a later suite in the same
// run (e.g. tests/cli-doctor-bundle.test.ts) never sees a dist/ this file left mid-mutation.
function ensureBundleSizesExists(): void {
  if (existsSync(bundleSizesPath)) return;
  const stdout = execFileSync(process.execPath, ['scripts/measure-bundles.mjs', '--json'], {
    cwd: root,
    encoding: 'utf8',
  });
  writeFileSync(bundleSizesPath, stdout);
}

describe('H4: dist/bundle-sizes.json ships inside the packed tarball', () => {
  test('package.json "files" contains a glob that matches dist/**/*.json', () => {
    const pkg = JSON.parse(readFileSync(resolve(root, 'package.json'), 'utf8'));
    const files: string[] = pkg.files ?? [];
    const hasJsonGlob = files.some((f) => /^dist\/.*\*\*?.*\.json$/.test(f) || f === 'dist/**/*.json');
    expect(hasJsonGlob).toBe(true);
  });

  test('package.json wires bundle-size generation to `prepack`, the hook that fires for both `npm pack` and `npm publish` (not only `prepublishOnly`, which npm never runs for `npm pack`)', () => {
    const pkg = JSON.parse(readFileSync(resolve(root, 'package.json'), 'utf8'));
    expect(pkg.scripts?.prepack).toMatch(/generate:bundle-sizes/);
  });

  test('a REAL `npm pack` (no --dry-run) regenerates and ships dist/bundle-sizes.json even when it was missing beforehand — the exact regression scenario', () => {
    // Reproduce the regression precondition: the artifact absent on disk before
    // packing (e.g. a fresh checkout that ran `npm run build` but never manually
    // ran `generate:bundle-sizes`).
    if (existsSync(bundleSizesPath)) {
      unlinkSync(bundleSizesPath);
    }
    expect(existsSync(bundleSizesPath)).toBe(false);

    const packDestination = mkdtempSync(join(tmpdir(), 'mdp-pack-test-'));
    try {
      // Deliberately NOT --dry-run: --dry-run skips lifecycle scripts (prepack
      // never runs), so it can only prove "an existing file would be included",
      // not "packing produces the file". That gap is exactly how this regressed
      // once already, so it must not be the thing this test relies on.
      execFileSync('npm', ['pack', '--pack-destination', packDestination], {
        cwd: root,
        encoding: 'utf8',
      });

      // `prepack` must have regenerated the file as a side effect of packing.
      expect(existsSync(bundleSizesPath)).toBe(true);

      const tarballName = readdirSync(packDestination).find((f) => f.endsWith('.tgz'));
      expect(tarballName).toBeDefined();

      const tarList = execFileSync('tar', ['tzf', join(packDestination, tarballName as string)], {
        encoding: 'utf8',
      });
      expect(tarList.split('\n')).toContain('package/dist/bundle-sizes.json');
    } finally {
      rmSync(packDestination, { recursive: true, force: true });
      ensureBundleSizesExists();
    }
  });

  test('npm pack --dry-run --json reports dist/bundle-sizes.json as an included file once it exists', () => {
    ensureBundleSizesExists();
    expect(existsSync(bundleSizesPath)).toBe(true);

    const dryRunOut = execFileSync('npm', ['pack', '--dry-run', '--json'], { cwd: root, encoding: 'utf8' });
    const parsed = JSON.parse(dryRunOut);
    const fileList: string[] = parsed[0]?.files?.map((f: { path: string }) => f.path) ?? [];

    expect(fileList).toContain('dist/bundle-sizes.json');
  });
});
