/**
 * @jest-environment node
 *
 * H4 (fix-2.2.0-blockers) — `dist/bundle-sizes.json` is generated by
 * `generate:bundle-sizes`, but no glob in `package.json`'s `files` array
 * matched a `.json` under `dist/`, so `npm pack` silently dropped it from
 * every published tarball. `src/cli/index.cjs` reads exactly
 * `node_modules/minder-data-provider/dist/bundle-sizes.json` — the path
 * README.md tells users to invoke via `npx minder doctor --bundle` — so
 * every real install had a broken command. That glob fix (`dist/**\/*.json`
 * in `files`) is still correct and is asserted below.
 *
 * REGRESSION (this program, FIX-B) — the glob was fine, but the file it
 * matches was regenerated by `generate:bundle-sizes` was only ever wired to
 * `prepublishOnly`. npm's lifecycle only runs `prepublishOnly` for
 * `npm publish` — it does NOT run for a bare `npm pack`. This repo's release
 * process never runs `npm publish` from CI or from an agent (owner-run,
 * manual step — see RELEASING.md); every "packed tarball" used for
 * validation in this repo is produced with `npm pack`. So the file was
 * generated for a code path (`npm publish`) that never actually executes
 * here, and omitted from every artifact that does (`npm pack`).
 *
 * Confirmed by direct repro (see task report): deleting `dist/bundle-sizes.json`
 * and running a REAL `npm pack` (no `--dry-run`, which skips lifecycle
 * scripts entirely and therefore cannot exercise this bug at all) produced a
 * tarball containing only `package/package.json` under `*.json` — the file
 * never came back, because nothing in the `npm pack` lifecycle regenerates it.
 *
 * FIX: `prepack` — the one npm lifecycle script that fires for BOTH
 * `npm pack` and `npm publish` — now runs `generate:bundle-sizes`. This is
 * the single choke point every packing path goes through; `prepublishOnly`
 * keeps its own call too (harmless — generation is idempotent) so a bare
 * `npm publish` still gets a guaranteed-fresh file before its full gate runs.
 *
 * Test posture: this suite proves the fix with a REAL (non-dry-run) `npm
 * pack`, because `--dry-run` never executes lifecycle scripts and so cannot
 * distinguish "the file happens to exist already" from "packing regenerates
 * it" — which is exactly the distinction that let this regress once already.
 * Guarded with a hard `existsSync(dist)` throw, not a skip — same posture as
 * every other file in this directory (see cjs-no-esm-dynamic-import.test.ts's
 * header for why).
 */
import { execFileSync } from 'node:child_process';
import {
  cpSync,
  existsSync,
  mkdtempSync,
  readdirSync,
  readFileSync,
  rmSync,
  symlinkSync,
  unlinkSync,
  writeFileSync,
} from 'node:fs';
import { tmpdir } from 'node:os';
import { join, resolve } from 'node:path';

const root = resolve(__dirname, '../..');
const distDir = resolve(root, 'dist');
const bundleSizesPath = resolve(distDir, 'bundle-sizes.json');

if (!existsSync(distDir)) {
  throw new Error(
    `tests/packaging expects dist/ to exist (found nothing at ${distDir}). ` +
      'This suite must run AFTER `npm run build`, never standalone.',
  );
}

// FIX-C (packaging-suite flake): `test:packaging` runs every file in this
// directory as a SEPARATE, PARALLEL jest worker (see package.json's
// `test:packaging` script — no `--runInBand`). The test below used to
// `unlinkSync` the real, shared `dist/bundle-sizes.json`, run a real `npm
// pack` against the REAL project root, and rely on `prepack` to regenerate
// it there — mutating the one checked-out `dist/` every other packaging
// worker also reads. `optional-peer-devtools.test.ts` (a sibling worker)
// recursively `cpSync`s that entire shared `dist/` tree at module load time;
// if its directory walk lists `bundle-sizes.json` and then, before it
// actually copies that file, the destructive test here has already
// `unlinkSync`'d it, the copy throws ENOENT — reproduced failing 2 of 3
// parallel runs, clean 3 of 3 under `--runInBand` (confirming it's a
// same-shared-directory race, not a genuine defect in either test).
//
// Fix: give this test its own scratch PROJECT COPY instead of mutating the
// shared `dist/` at all. `npm pack`'s `prepack` hook only needs
// `package.json`, `dist/`, and `scripts/` (what `generate:bundle-sizes`
// actually reads/writes) to run for real; `bin/`, `src/cli`, `README.md`,
// `LICENSE`, and `llms.txt` are copied too only so the packed tarball's
// shape matches a real `npm pack` (they're `files`-glob entries `npm pack`
// would otherwise just skip, not a hard requirement for `prepack` itself).
// `node_modules` is SYMLINKED, not copied — `generate:bundle-sizes` needs
// `esbuild` resolvable but copying ~400MB of node_modules per test run
// would be its own new cost, not a fix. This is now a REAL `npm pack`
// (lifecycle scripts run, unlike `--dry-run`) — it just runs against an
// isolated copy of the shipped surface instead of the live, shared one, so
// no other worker ever observes the mid-test absence of the file.
function stagePackableProject(): string {
  const work = mkdtempSync(join(tmpdir(), 'mdp-pack-project-'));
  cpSync(resolve(root, 'package.json'), join(work, 'package.json'));
  cpSync(distDir, join(work, 'dist'), { recursive: true });
  cpSync(resolve(root, 'scripts'), join(work, 'scripts'), { recursive: true });
  for (const optional of ['bin', 'src/cli', 'README.md', 'LICENSE', 'llms.txt']) {
    const src = resolve(root, optional);
    if (existsSync(src)) {
      cpSync(src, join(work, optional), { recursive: true });
    }
  }
  // 'dir' is the correct symlink type for a directory target; Node only
  // consults this argument on Windows and ignores it on POSIX (Linux/macOS,
  // what this repo's CI and local dev both run).
  symlinkSync(resolve(root, 'node_modules'), join(work, 'node_modules'), 'dir');
  return work;
}

// Regenerates dist/bundle-sizes.json directly (mirrors the `generate:bundle-sizes`
// npm script) — used only as a post-test safety net so a later suite in the same
// run (e.g. tests/cli-doctor-bundle.test.ts) never sees a dist/ this file left mid-mutation.
function ensureBundleSizesExists(): void {
  if (existsSync(bundleSizesPath)) return;
  const stdout = execFileSync(process.execPath, ['scripts/measure-bundles.mjs', '--json'], {
    cwd: root,
    encoding: 'utf8',
  });
  writeFileSync(bundleSizesPath, stdout);
}

describe('H4: dist/bundle-sizes.json ships inside the packed tarball', () => {
  test('package.json "files" contains a glob that matches dist/**/*.json', () => {
    const pkg = JSON.parse(readFileSync(resolve(root, 'package.json'), 'utf8'));
    const files: string[] = pkg.files ?? [];
    const hasJsonGlob = files.some((f) => /^dist\/.*\*\*?.*\.json$/.test(f) || f === 'dist/**/*.json');
    expect(hasJsonGlob).toBe(true);
  });

  test('package.json wires bundle-size generation to `prepack`, the hook that fires for both `npm pack` and `npm publish` (not only `prepublishOnly`, which npm never runs for `npm pack`)', () => {
    const pkg = JSON.parse(readFileSync(resolve(root, 'package.json'), 'utf8'));
    expect(pkg.scripts?.prepack).toMatch(/generate:bundle-sizes/);
  });

  test('a REAL `npm pack` (no --dry-run) regenerates and ships dist/bundle-sizes.json even when it was missing beforehand — the exact regression scenario', () => {
    // Isolated project copy (see stagePackableProject's doc comment above) —
    // this test mutates a scratch `dist/bundle-sizes.json`, never the real,
    // shared one every other parallel packaging-suite worker also reads.
    const stagedRoot = stagePackableProject();
    const stagedBundleSizesPath = resolve(stagedRoot, 'dist', 'bundle-sizes.json');

    // Reproduce the regression precondition: the artifact absent on disk before
    // packing (e.g. a fresh checkout that ran `npm run build` but never manually
    // ran `generate:bundle-sizes`).
    if (existsSync(stagedBundleSizesPath)) {
      unlinkSync(stagedBundleSizesPath);
    }
    expect(existsSync(stagedBundleSizesPath)).toBe(false);

    const packDestination = mkdtempSync(join(tmpdir(), 'mdp-pack-test-'));
    try {
      // Deliberately NOT --dry-run: --dry-run skips lifecycle scripts (prepack
      // never runs), so it can only prove "an existing file would be included",
      // not "packing produces the file". That gap is exactly how this regressed
      // once already, so it must not be the thing this test relies on.
      execFileSync('npm', ['pack', '--pack-destination', packDestination], {
        cwd: stagedRoot,
        encoding: 'utf8',
      });

      // `prepack` must have regenerated the file as a side effect of packing.
      expect(existsSync(stagedBundleSizesPath)).toBe(true);

      const tarballName = readdirSync(packDestination).find((f) => f.endsWith('.tgz'));
      expect(tarballName).toBeDefined();

      const tarList = execFileSync('tar', ['tzf', join(packDestination, tarballName as string)], {
        encoding: 'utf8',
      });
      expect(tarList.split('\n')).toContain('package/dist/bundle-sizes.json');
    } finally {
      rmSync(packDestination, { recursive: true, force: true });
      // node_modules is a symlink into the real, shared install — rmSync
      // without `recursive` following into it would delete the real thing.
      // `force: true` alone is safe here: Node's recursive rm removes the
      // symlink entry itself, never dereferences it into the target directory.
      rmSync(stagedRoot, { recursive: true, force: true });
    }
  });

  test('npm pack --dry-run --json reports dist/bundle-sizes.json as an included file once it exists', () => {
    ensureBundleSizesExists();
    expect(existsSync(bundleSizesPath)).toBe(true);

    const dryRunOut = execFileSync('npm', ['pack', '--dry-run', '--json'], { cwd: root, encoding: 'utf8' });
    const parsed = JSON.parse(dryRunOut);
    const fileList: string[] = parsed[0]?.files?.map((f: { path: string }) => f.path) ?? [];

    expect(fileList).toContain('dist/bundle-sizes.json');
  });
});
