/**
 * Generated by tsnapi — public API snapshot of `minder-data-provider/auth`
 */
// #region Re-exports
export { _ as AuthConfig, _ as SessionData } from '../types-HASH.js';
export { _ as AuthManager } from '../AuthManager-HASH.js';
export { _ as CSRFToken, _ as JWTPayload, _ as SecureAuthConfig, _ as SecureAuthManager, _ as TokenRefreshConfig, _ as TokenRefreshManager, _ as UseAuthReturn, _ as createSecureAuthManager, _ as createTokenRefreshManager, _ as useAuth } from '../index-HASH.js';
export { _ as useAuthToken, _ as useCurrentUser } from '../index-HASH.js';
// #endregion