/**
 * Generated by tsnapi — public API snapshot of `minder-data-provider/auth`
 */
// #region Interfaces
export interface CSRFToken {
    token: string;
    timestamp: number;
}
export interface JWTPayload {
    exp?: number;
    iat?: number;
    sub?: string;
    [key: string]: any;
}
export interface SecureAuthConfig extends Partial<AuthConfig> {
    tokenKey?: string;
    storage?: StorageType;
    enforceHttps?: boolean;
    enableCSRF?: boolean;
    cookieOptions?: {
        httpOnly?: boolean;
        secure?: boolean;
        sameSite?: 'strict' | 'lax' | 'none';
        maxAge?: number;
        domain?: string;
        path?: string;
    };
    autoRefresh?: boolean;
    refreshBeforeExpiry?: number;
    rateLimit?: {
        maxAttempts: number;
        windowMs: number;
    };
}
export interface TokenRefreshConfig {
    refreshThreshold?: number;
    refreshToken: () => Promise<string>;
    onTokenRefreshed?: (_: string) => void;
    onRefreshError?: (_: Error) => void;
    enabled?: boolean;
    debug?: boolean;
}
// #endregion

// #region Classes
export declare class SecureAuthManager extends AuthManager {
    private secureConfig;
    private csrfToken;
    private csrfTimestamp;
    private refreshTimer;
    private rateLimitAttempts;
    constructor(_?: SecureAuthConfig, _?: DebugManager, _?: boolean);
    private generateCSRFToken;
    getCSRFToken(): string;
    validateCSRFToken(_: string): boolean;
    setToken(_: string): void;
    private parseJWT;
    private scheduleTokenRefresh;
    refreshTokens(): Promise<void>;
    private sanitizeInput;
    sanitizeEmail(_: string): string;
    sanitizeURL(_: string): string;
    private checkRateLimit;
    login(_: {
        email: string;
        password: string;
    }): Promise<boolean>;
    clearAuth(): void;
    destroy(): void;
    setHttpOnlyCookie(_: string, _: string): string;
    getSecurityHeaders(): Record<string, string>;
}
export declare class TokenRefreshManager {
    private config;
    private refreshTimer;
    private currentToken;
    private isRefreshing;
    constructor(_: TokenRefreshConfig);
    private parseJWT;
    private getExpirationTime;
    private getTimeUntilExpiration;
    isTokenExpired(_: string): boolean;
    needsRefresh(_: string): boolean;
    private scheduleRefresh;
    private performRefresh;
    startAutoRefresh(_: string): void;
    stopAutoRefresh(): void;
    refreshNow(): Promise<string | null>;
    getTokenInfo(_: string): {
        valid: boolean;
        expired: boolean;
        needsRefresh: boolean;
        expiresAt: Date | null;
        timeUntilExpiration: number | null;
        payload: JWTPayload | null;
    };
    updateConfig(_: Partial<TokenRefreshConfig>): void;
    dispose(): void;
}
// #endregion

// #region Functions
export declare function createSecureAuthManager(_?: SecureAuthConfig, _?: DebugManager, _?: boolean): SecureAuthManager;
export declare function createTokenRefreshManager(_: TokenRefreshConfig): TokenRefreshManager;
// #endregion

// #region Re-exports
export { _ as SessionData } from '../types-HASH.js';
export { _ as useAuth, _ as useCurrentUser } from '../index-HASH.js';
// #endregion

// #region Other
export { AuthConfig }
export { AuthManager }
// #endregion