/**
 * Generated by tsnapi — public API snapshot of `minder-data-provider/config`
 */
// #region Interfaces
export interface UnifiedMinderConfig {
    apiUrl: string;
    baseURL?: string;
    routes?: Record<string, string | ApiRoute>;
    providers?: Record<string, unknown>;
    dynamic?: any;
    plugins?: MinderPlugin[];
    auth?: boolean | {
        storage?: StorageType;
        tokenKey?: string;
        refreshUrl?: string;
        authHeader?: string;
        authTokenPrefix?: string;
    };
    cache?: boolean | {
        staleTime?: number;
        gcTime?: number;
        refetchOnWindowFocus?: boolean;
        refetchOnReconnect?: boolean;
        ttl?: number;
        type?: CacheType;
        maxSize?: number;
    };
    cors?: boolean | {
        enabled?: boolean;
        proxy?: string;
    };
    corsHelper?: boolean | {
        enabled?: boolean;
        proxy?: string;
        credentials?: boolean;
        origin?: string;
        methods?: string[];
        headers?: string[];
    };
    websocket?: boolean | {
        url?: string;
        reconnect?: boolean;
        heartbeat?: number;
    };
    security?: boolean | {
        csrfProtection?: boolean;
        sanitization?: boolean;
        rateLimiting?: {
            requests: number;
            window: number;
        };
    };
    debug?: boolean | {
        enabled?: boolean;
        logLevel?: LogLevel;
        performance?: boolean;
        devTools?: boolean;
        networkLogs?: boolean;
        authLogs?: boolean;
        cacheLogs?: boolean;
        websocketLogs?: boolean;
    };
    performance?: {
        deduplication?: boolean;
        retries?: number;
        timeout?: number;
        compression?: boolean;
    };
    ssr?: boolean | {
        enabled?: boolean;
        prefetch?: string[];
    };
    offline?: OfflineConfig;
    environments?: Record<string, {
        apiUrl?: string;
        cors?: {
            proxy?: string;
        };
        debug?: boolean;
    }>;
    transport?: 'auto' | 'axios' | 'fetch';
}
// #endregion

// #region Classes
export declare class OfflineManager {
    private config;
    private queue;
    private networkState;
    private isSyncing;
    private syncPromise;
    private netInfoUnsubscribe?;
    private listeners;
    private initPromise;
    private requestExecutor?;
    private destroyController;
    private warnedBothResolversConfigured;
    constructor(_?: OfflineConfig);
    setRequestExecutor(_: (_: QueuedRequest) => Promise<unknown>): void;
    initialize(): Promise<void>;
    private doInitialize;
    private setupNetworkListener;
    private setupFallbackNetworkListener;
    checkNetworkState(): Promise<NetworkState>;
    private updateNetworkState;
    addToQueue(_: QueuedRequest['method'], _: string, _?: {
        headers?: Record<string, string>;
        body?: any;
        priority?: number;
        maxRetries?: number;
        metadata?: Record<string, unknown>;
    }): Promise<string>;
    removeFromQueue(_: string): Promise<boolean>;
    getQueue(): QueuedRequest[];
    getQueueSize(): number;
    clearQueue(): Promise<void>;
    getNetworkState(): NetworkState;
    isOnline(): boolean;
    isSyncInProgress(): boolean;
    subscribe(_: OfflineManagerListener): () => void;
    getSnapshot(): OfflineManagerSnapshot;
    private notify;
    sync(): Promise<SyncStats>;
    private emitSyncHook;
    private performSync;
    private processQueuedRequest;
    private executeRequest;
    private interpretExecutorResult;
    private resolveConflictAndApply;
    private effectiveConflictStrategy;
    private isConflictStrategy;
    private isValidConflictResolution;
    private dispatchConflictStrategy;
    private invokeResolver;
    private createConflictSignal;
    private raceAgainstAbort;
    private toAbortError;
    private handleRequestError;
    private appendDeadLetter;
    private createBatches;
    private sortQueueByPriority;
    private saveQueue;
    private loadQueue;
    private generateId;
    destroy(): Promise<void>;
}
// #endregion

// #region Functions
export declare function __resetBaseUrlAliasWarning(): void;
export declare function __resetNextjsDynamicWarning(): void;
export declare function configureMinder(_: UnifiedMinderConfig): MinderConfig;
export declare function createConfigFromPreset(_: ConfigPreset, _?: Partial<MinderConfig>): Partial<MinderConfig>;
export declare function getOfflineManager(): OfflineManager | null;
export declare function getPresetInfo(_: ConfigPreset): {
    name: string;
    description: string;
    bundleSize: string;
    features: string[];
    useCase: string;
} | {
    name: string;
    description: string;
    bundleSize: string;
    features: string[];
    useCase: string;
} | {
    name: string;
    description: string;
    bundleSize: string;
    features: string[];
    useCase: string;
} | {
    name: string;
    description: string;
    bundleSize: string;
    features: string[];
    useCase: string;
} | {
    name: string;
    description: string;
    bundleSize: string;
    features: string[];
    useCase: string;
} | {
    name: string;
    description: string;
    bundleSize: string;
    features: string[];
    useCase: string;
};
// #endregion

// #region Re-exports
export { _ as CorsHelperConfig, _ as EnvironmentOverride } from '../types-HASH.js';
// #endregion

// #region Other
export { ApiRoute }
export { ConfigPreset }
export { MinderConfig }
// #endregion