/**
 * Generated by tsnapi — public API snapshot of `minder-data-provider/core`
 */
// #region Re-exports
export { configureMinder } from './config/index.js';
export { _ as minder } from './minder-HASH.js';
export { _ as MinderAuthError, _ as MinderConfigError, _ as MinderError, _ as MinderNetworkError, _ as MinderOptions, _ as MinderRequestError, _ as MinderResult, _ as MinderTimeoutError, _ as MinderValidationError, _ as UploadProgress, _ as getErrorCode, _ as getErrorMessage, _ as isMinderError } from './MinderError-HASH.js';
export { _ as MinderDataProvider, _ as useMinder, _ as useMinderContext } from './index-HASH.js';
// #endregion