/**
 * Generated by tsnapi — public API snapshot of `minder-data-provider/crud`
 */
// #region Re-exports
export { _ as CrudOperations } from '../types-HASH.js';
export { _ as useOneTouchCrud } from '../index-HASH.js';
// #endregion