/**
 * Generated by tsnapi — public API snapshot of `minder-data-provider/debug`
 */
// #region Functions
export declare function useDebug(): {
    log: (_: DebugLogType, _: string, _?: unknown) => void | undefined;
    startTimer: (_: string) => void | undefined;
    endTimer: (_: string) => void | undefined;
    getLogs: () => DebugLogEntry[];
    clearLogs: () => void | undefined;
    getPerformanceMetrics: () => [string, number][];
};
// #endregion

// #region Re-exports
export { _ as DebugManager } from '../DebugManager-HASH.js';
// #endregion