/**
 * Generated by tsnapi — public API snapshot of `minder-data-provider/devtools-rq`
 */
// #region Types
export type ReactQueryDevtoolsProps = ComponentProps<typeof ReactQueryDevtools$1>;
// #endregion

// #region Functions
export declare function loadReactQueryDevtools(): Promise<typeof ReactQueryDevtools>;
// #endregion

// #region Re-exports
export { DevtoolsPanelOptions, ReactQueryDevtools, ReactQueryDevtoolsPanel } from '@tanstack/react-query-devtools';
// #endregion