/**
 * Generated by tsnapi — public API snapshot of `minder-data-provider/hook`
 */
// #region Re-exports
export { _ as MinderDataProvider, _ as UseMinderOptions, _ as UseMinderReturn, _ as default, _ as useMinder, _ as useMinderContext } from './index-HASH.js';
export { _ as MinderError, _ as getErrorCode, _ as getErrorMessage, _ as isMinderError } from './MinderError-HASH.js';
// #endregion