/**
 * Generated by tsnapi — public API snapshot of `minder-data-provider`
 */
// #region Interfaces
export interface AuthContract {
    getSession(): Promise<{
        userId: string;
        raw: unknown;
    } | null>;
    signOut(): Promise<void>;
}
export interface CustomProvider<TConfig, TClient> {
    readonly providerName: string;
    readonly capability: Capability;
    register(_: TConfig): () => void;
    getClient(): TClient | null;
}
export interface DefineProviderOptions<TContract, TConfig = {
    mock?: boolean;
}, TClient = unknown> {
    providerName: string;
    capability: Capability;
    createClient(_: TConfig): TClient;
    toContract(_: TClient, _: TConfig): TContract;
    isMock?(_: TConfig): boolean;
    createMock?(_: TConfig): TContract;
}
export interface DynamicLoaderConfig {
    preload?: ('query' | 'axios')[];
    cache?: boolean;
    debug?: boolean;
}
export interface ErrorBoundaryProps {
    children: ReactNode;
    fallback?: ReactNode | ((_: Error, _: ErrorInfo) => ReactNode);
    onError?: (_: Error, _: ErrorInfo) => void;
    resetKeys?: Array<string | number>;
    onReset?: () => void;
    ariaLabel?: string;
}
export interface LiveContract {
    subscribe(_: string, _: (_: unknown) => void): () => void;
}
export interface PageData<TData = any> {
    data: TData[];
    page?: number;
    cursor?: string | number;
    hasNext?: boolean;
    hasPrevious?: boolean;
    total?: number;
}
export interface PaginationConfig<TData = any> {
    type: 'offset' | 'cursor';
    pageSize?: number;
    initialPage?: number;
    pageParam?: string;
    limitParam?: string;
    cursorParam?: string;
    getCursor?: (_: TData) => string | number | undefined;
    getNextPageParam?: (_: MinderResult<TData[]>) => any;
    getPreviousPageParam?: (_: MinderResult<TData[]>) => any;
}
export interface PaymentsContract {
    createCheckout(_: {
        items: unknown[];
        successUrl: string;
        cancelUrl: string;
    }): Promise<{
        url: string;
    }>;
}
export interface RateLimitConfig {
    max?: number;
    windowMs?: number;
    message?: string;
    statusCode?: number;
    skip?: (_: string) => boolean;
    keyGenerator?: (_: any) => string;
    onLimitReached?: (_: string, _: any) => void;
}
export interface StorageContract {
    upload(_: Blob | {
        uri: string;
    }, _: string): Promise<{
        url: string;
    }>;
    remove(_: string): Promise<void>;
}
export interface TypedRoute<TResponse> {
    url: string;
    method?: HttpMethod$1;
    readonly __response?: TResponse;
}
export interface UsePaginatedMinderOptions<TData = any> extends MinderOptions<TData[]> {
    pagination: PaginationConfig<TData>;
    autoFetch?: boolean;
    refetchOnWindowFocus?: boolean;
    refetchOnReconnect?: boolean;
    enabled?: boolean;
    queryOptions?: Omit<UseInfiniteQueryOptions<MinderResult<TData[]>>, 'queryKey' | 'queryFn' | 'getNextPageParam'>;
}
export interface UsePaginatedMinderReturn<TData = any> {
    data: TData[];
    pages: PageData<TData>[];
    loading: boolean;
    isFetchingNextPage: boolean;
    isFetchingPreviousPage: boolean;
    error: any;
    hasNextPage: boolean;
    hasPreviousPage: boolean;
    fetchNextPage: () => Promise<void>;
    fetchPreviousPage: () => Promise<void>;
    refetch: () => Promise<void>;
    invalidate: () => Promise<void>;
    total?: number;
    query: any;
}
// #endregion

// #region Types
export type HttpMethod = HttpMethod$1;
export type ResponseOf<T> = T extends TypedRoute<infer U> ? U : unknown;
// #endregion

// #region Classes
export declare class DynamicLoader {
    private static queryClient;
    private static axios;
    private static loading;
    private config;
    constructor(_?: DynamicLoaderConfig);
    loadQueryClient(): Promise<QueryClient>;
    getQueryClient(): any | null;
    isQueryClientLoaded(): boolean;
    loadAxios(): Promise<any>;
    getAxios(): any | null;
    isAxiosLoaded(): boolean;
    loadAll(): Promise<void>;
    areAllLoaded(): boolean;
    getLoadingStatus(): {
        queryClient: boolean;
        axios: boolean;
        all: boolean;
    };
    static clearCache(): void;
    static getBundleSavings(): {
        queryClient: number;
        axios: number;
        total: number;
    };
}
export declare class GlobalAuthManager {
    private token;
    private refreshToken;
    private user;
    private storage;
    private tokenKey;
    private refreshTokenKey;
    constructor(_?: GlobalAuthConfig);
    private restoreFromStorage;
    private parseJWT;
    setToken(_: string): Promise<void>;
    getToken(): string | null;
    setRefreshToken(_: string): Promise<void>;
    getRefreshToken(): string | null;
    clearAuth(): Promise<void>;
    isAuthenticated(): boolean;
    getCurrentUser(): any;
    isTokenExpired(): boolean;
    getTokenExpiryTime(): number | null;
}
export declare class LocalStore {
    private adapter;
    constructor(_?: StorageAdapter);
    get<T = unknown>(_: unknown): Promise<T | null>;
    set<T = unknown>(_: unknown, _: T): Promise<void>;
    remove(_: unknown): Promise<void>;
}
export declare class MemoryRateLimitStore {
    private store;
    private cleanupInterval;
    constructor();
    increment(_: string, _: number): Promise<RateLimitEntry>;
    get(_: string): Promise<RateLimitEntry | null>;
    reset(_: string): Promise<void>;
    private cleanup;
    getStats(): {
        totalEntries: number;
        activeEntries: number;
    };
    dispose(): void;
}
export declare class MinderErrorBoundary extends Component<ErrorBoundaryProps, ErrorBoundaryState> {
    constructor(_: ErrorBoundaryProps);
    static getDerivedStateFromError(_: Error): Partial<ErrorBoundaryState>;
    componentDidCatch(_: Error, _: ErrorInfo): void;
    componentDidUpdate(_: ErrorBoundaryProps): void;
    reset: () => void;
    render(): ReactNode;
}
export declare class PerformanceMonitor {
    private metrics;
    private cacheHits;
    private cacheMisses;
    private errors;
    private totalRequests;
    recordLatency(_: string, _: number): void;
    recordCacheHit(): void;
    recordCacheMiss(): void;
    recordError(): void;
    getMetrics(): PerformanceMetrics;
    private getMemoryUsage;
    reset(): void;
}
export declare class RateLimiter {
    private config;
    private store;
    constructor(_?: RateLimitConfig, _?: MemoryRateLimitStore);
    private defaultKeyGenerator;
    check(_: any): Promise<{
        allowed: boolean;
        remaining: number;
        resetTime: number;
        total: number;
    }>;
    reset(_: string): Promise<void>;
    getStats(): {
        totalEntries: number;
        activeEntries: number;
    };
    dispose(): void;
}
export declare class RequestBatcher {
    private queue;
    private timers;
    private batchDelay;
    constructor(_?: number);
    add(_: string, _: () => Promise<any>): Promise<any>;
    private flush;
    clear(): void;
}
export declare class RequestDeduplicator {
    private pending;
    private maxAge;
    constructor(_?: number);
    deduplicate<T>(_: string, _: () => Promise<T>): Promise<T>;
    clear(): void;
}
// #endregion

// #region Functions
export declare function clearAllUploadProgress(): void;
export declare function clearGlobalMinderConfig(): void;
export declare function clearUploadProgress(_: string): void;
export declare function createCorsConfig(_?: {
    origin?: string | string[];
    credentials?: boolean;
    methods?: string[];
}): any;
export declare function createDynamicLoader(_?: DynamicLoaderConfig): DynamicLoader;
export declare function createExpressRateLimiter(_?: RateLimitConfig): (_: any, _: any, _: () => void) => Promise<void>;
export declare function createLightConfig(_: LightConfig): MinderConfig & {
    validation: ConfigValidationResult;
};
export declare function createNextRateLimiter(_?: RateLimitConfig): (_: any, _: any, _?: () => void) => Promise<any>;
export declare function createRateLimiter(_?: RateLimitConfig): RateLimiter;
export declare function createTypedMinder<R extends Record<string, TypedRoute<any>>>(_: R): {
    minder: TypedMinderFn<R>;
    useMinder: <K extends keyof R>(_: K, _?: UseMinderOptions) => UseMinderReturn<ResponseOf<R[K]>>;
};
export declare function debounce<T extends (...args: any[]) => any>(_: T, _: number): (..._: Parameters<T>) => void;
export declare function deepMerge<T extends Record<string, unknown> = Record<string, unknown>>(_: T, _: Record<string, unknown>): T;
export declare function defineProvider<TContract, TConfig = {
    mock?: boolean;
}, TClient = unknown>(_: DefineProviderOptions<TContract, TConfig, TClient>): CustomProvider<TConfig, TClient>;
export declare function extractParamNames(_: string): string[];
export declare function formatApiError(_: unknown): string;
export declare function formatFileSize(_: number): string;
export declare function generateId(): string;
export declare function getAllUploadProgress(): Record<string, UploadProgress>;
export declare function getBundleSizeImpact(_: string[]): {
    estimatedSize: number;
    recommendations: string[];
};
export declare function getDefaultLocalStore(): LocalStore;
export declare function getDynamicLoader(_?: DynamicLoaderConfig): DynamicLoader;
export declare function getGlobalMinderConfig(): MinderConfig | null;
export declare function getRouteSuggestions(_: string, _: string[], _?: number): string[];
export declare function getUploadProgress(_: string): UploadProgress;
export declare function hasGlobalMinderConfig(): boolean;
export declare function hasUnreplacedParams(_: string): boolean;
export declare function isValidEmail(_: string): boolean;
export declare function isValidUrl(_: string): boolean;
export declare function levenshteinDistance(_: string, _: string): number;
export declare function localKeyOf(_: unknown): string;
export declare function mergeMinderConfig(..._: PartialConfig[]): UnifiedMinderConfig;
export declare function replaceUrlParams(_: string, _?: Record<string, unknown>): string;
export declare function retry<T>(_: () => Promise<T>, _?: number, _?: number): Promise<T>;
export declare function route<TResponse>(_: string, _?: {
    method?: HttpMethod$1;
}): TypedRoute<TResponse>;
export declare function setGlobalMinderConfig(_: MinderConfig): void;
export declare function setUploadProgress(_: string, _: UploadProgress): void;
export declare function subscribeToUploadProgress(_: string, _: (_: UploadProgress) => void): () => void;
export declare function throttle<T extends (...args: any[]) => any>(_: T, _: number): (..._: Parameters<T>) => void;
export declare function toCamelCase(_: string): string;
export declare function toSnakeCase(_: string): string;
export declare function useAbortController(): AbortController;
export declare function useConfiguration(_?: ConfigurationOptions): {
    config: MinderConfig;
    upgradeToFull: () => MinderConfig;
    updateFeature: <K extends keyof MinderConfig>(_: K, _: Partial<MinderConfig[K]>) => void;
    optimizeForCurrentUsage: () => void;
    metrics: {
        performance: {
            apiLatency: number;
            cacheHitRate: number;
            bundleSize: number;
            memoryUsage: number;
        };
        security: {
            failedAuthAttempts: number;
            rateLimitHits: number;
            suspiciousRequests: number;
        };
    };
};
export declare function useDebounce<T>(_: T, _?: number): T;
export declare function useEnvironment(): {
    currentEnvironment: string;
    setEnvironment: (_: string) => void;
    getAllEnvironments: () => string[];
    isProduction: () => boolean;
    isDevelopment: () => boolean;
    getDebugMode: () => boolean;
    getEnvironmentConfig: () => EnvironmentOverride | null;
    isHydrated: boolean;
};
export declare function useErrorHandler<T = Error>(_?: T | null | undefined): (_: T) => void;
export declare function useLazyLoad<T>(_: () => Promise<T>, _?: {
    threshold?: number;
    rootMargin?: string;
}): {
    data: T | null;
    loading: boolean;
    error: Error | null;
};
export declare function useMemoizedCallback<T extends (...args: any[]) => any>(_: T, _: DependencyList): T;
export declare function usePaginatedMinder<TData = any>(_: string, _: UsePaginatedMinderOptions<TData>): UsePaginatedMinderReturn<TData>;
export declare function usePerformanceMonitor(_: string): {
    renderCount: number;
    averageRenderTime: number;
};
export declare function useProxy(): {
    isEnabled: () => boolean;
    generateNextJSProxy: () => string;
};
export declare function useThrottle<T>(_: T, _?: number): T;
export declare function useUnmountCleanup(_: () => void): void;
export declare function validateRoutes(_: Record<string, ApiRoute>): RouteValidationResult;
// #endregion

// #region Variables
export declare const globalAuthManager: GlobalAuthManager;
export declare const RateLimitPresets: {
    readonly strict: {
        readonly max: 5;
        readonly windowMs: number;
        readonly message: "Too many requests to sensitive endpoint";
    };
    readonly moderate: {
        readonly max: 100;
        readonly windowMs: number;
    };
    readonly lenient: {
        readonly max: 1000;
        readonly windowMs: number;
    };
    readonly perHour: {
        readonly max: 1000;
        readonly windowMs: number;
    };
};
// #endregion

// #region Re-exports
export { _ as AnalyticsConfig, _ as AnalyticsPlugin, _ as ApiError, _ as AuthConfig, _ as BaseModel, _ as CacheConfig, _ as CacheEntry, _ as CacheHitEvent, _ as CacheWarmupPlugin, _ as CorsConfig, _ as CorsHelperConfig, _ as CrudOperations, _ as DebugConfig, _ as InferInput, _ as LoggerPlugin, _ as MediaUploadResult, _ as MinderPlugin, _ as Notification, _ as PerformanceConfig, _ as PerformanceMonitorPlugin, _ as PluginError, _ as PluginManager, _ as PluginRequest, _ as PluginResponse, _ as QueryState, _ as RealtimeConfig, _ as RealtimeReconnectConfig, _ as RetryConfig, _ as RetryPlugin, _ as SSRConfig, _ as SecurityConfig, _ as ServerState, _ as SessionData, _ as TelemetryConfig, _ as UIState, _ as UserState, _ as WebSocketConfig, _ as createPlugin, _ as pluginManager, _ as registerPlugins } from './types-HASH.js';
export { _ as AuthManager } from './AuthManager-HASH.js';
export { _ as AuthState, _ as CacheRequirements, _ as CacheType, _ as ConfigPreset, _ as ConfigPresetType, _ as CrudOperation, _ as DEFAULT_VALUES, _ as DataSize, _ as DataSizeType, _ as EVENTS, _ as Environment, _ as ErrorCode, _ as HTTP_STATUS, _ as HttpMethodType, _ as LogLevel, _ as LogLevelType, _ as MIME_TYPES, _ as NetworkState, _ as NotificationType, _ as NotificationTypeType, _ as PaginationType, _ as Platform, _ as PlatformType, _ as PrefetchStrategy, _ as QueryStatus, _ as QueryStatusType, _ as RetryStrategy, _ as STORAGE_KEYS, _ as SecurityLevel, _ as SecurityLevelType, _ as SortOrder, _ as StorageType, _ as StorageTypeType, _ as TokenType, _ as UploadState, _ as WebSocketState, _ as isConfigPreset, _ as isDataSize, _ as isHttpMethod, _ as isLogLevel, _ as isPlatform, _ as isQueryStatus, _ as isSecurityLevel, _ as isStorageType } from './enums-HASH.js';
export { _ as BatchedRequest, _ as PendingRequest, _ as ProxyConfig, _ as ProxyManager } from './ApiClient-HASH.js';
export { _ as CacheManager } from './CacheManager-HASH.js';
export { _ as CapabilityProvider, _ as UseAuthReturn, _ as UseCheckoutReturn, _ as UseLiveReturn, _ as UseStorageReturn, _ as getCapabilityProvider, _ as getProviderConfig, _ as registerCapabilityProvider, _ as registerClientSafeProviderKeys, _ as registerMockProvider, _ as subscribeCapabilityRegistry, _ as useAuth, _ as useCheckout, _ as useLive, _ as useStorage } from './validateConfig-HASH.js';
export { _ as CredentialInput, _ as ExposedSecret, _ as SecretRef, _ as assertNoExposedSecrets, _ as describeCredential, _ as env, _ as findExposedSecrets, _ as isCredentialInput, _ as isSecretRef, _ as redactSecrets, _ as secret } from './credentials-HASH.js';
export { CSRFToken, JWTPayload, SecureAuthConfig, SecureAuthManager, TokenRefreshConfig, TokenRefreshManager, createSecureAuthManager, createTokenRefreshManager } from './auth/index.js';
export { _ as DebugManager } from './DebugManager-HASH.js';
export { _ as DevTools, _ as DevToolsConfig, _ as DevToolsEvents, _ as PlatformDetector } from './DevTools-HASH.js';
export { _ as EnvironmentManager, _ as MinderDataProvider, _ as useMinder, _ as useMinderContext } from './index-HASH.js';
export { _ as FeatureFlags, _ as FeatureLoader, _ as FeatureLoaderOptions, _ as FeatureModules, _ as PlatformCapabilities, _ as PlatformCapabilityDetector, _ as createFeatureLoader } from './FeatureLoader-HASH.js';
export { _ as FilterOption, _ as PaginationHelper, _ as PaginationOptions, _ as PaginationResult, _ as PaginationState, _ as QueryBuilder, _ as QueryParams, _ as SortOption, _ as query, _ as usePagination, _ as useQueryBuilder } from './QueryBuilder-HASH.js';
export { HydrationBoundary, QueryClient, QueryClientProvider, dehydrate } from '@tanstack/react-query';
export { _ as Logger, _ as LoggerConfig, _ as createLogger, _ as defaultLogger } from './index-HASH.js';
export { MediaUploadManager, UploadOptions, UploadProgressDetails, createUploadManager } from './upload/index.js';
export { _ as minder } from './minder-HASH.js';
export { _ as MinderAuthError, _ as MinderAuthorizationError, _ as MinderConfigError, _ as MinderConflictError, _ as MinderError, _ as MinderNetworkError, _ as MinderOfflineError, _ as MinderPlatformError, _ as MinderPluginError, _ as MinderRequestError, _ as MinderSecurityError, _ as MinderStorageError, _ as MinderTimeoutError, _ as MinderUploadError, _ as MinderValidationError, _ as MinderWebSocketError, _ as UploadProgress, _ as getErrorCode, _ as getErrorMessage, _ as isMinderError } from './MinderError-HASH.js';
export { MinderResponseValidationError } from './core.js';
export { OfflineManager, __resetNextjsDynamicWarning, configureMinder, createConfigFromPreset, getOfflineManager, getPresetInfo } from './config/index.js';
export { _ as PROVIDER_CATEGORIES, _ as PROVIDER_FRAMEWORKS, _ as PROVIDER_RUNTIMES, _ as ProviderCapability, _ as ProviderCategory, _ as ProviderConfigSplit, _ as ProviderDocs, _ as ProviderFramework, _ as ProviderManifest, _ as ProviderRuntime, _ as ProviderScope, _ as ValidationResult, _ as defineProviderManifest, _ as providerManifestSchema, _ as validateProviderManifest } from './manifest-HASH.js';
export { SSROptions, createSSRConfig, getDehydratedState, prefetchData, withCSR, withSSR } from './ssr/index.js';
export { _ as useCache, _ as useCurrentUser, _ as useMediaUpload, _ as useOneTouchCrud, _ as useUIState, _ as useWebSocket } from './index-HASH.js';
export { useDebug } from './debug/index.js';
export { WebSocketClient, WebSocketEventHandler, WebSocketMessage, createWebSocketClient } from './websocket/index.js';
// #endregion

// #region Other
export { ApiRoute }
export { Capability }
export { EnvironmentOverride }
export { InferOutput }
export { MinderConfig }
export { MinderOptions }
export { MinderResult }
export { PerformanceMetrics }
export { StandardSchemaV1 }
export { UnifiedMinderConfig }
export { UseMinderOptions }
export { UseMinderReturn }
// #endregion