/**
 * Generated by tsnapi — public API snapshot of `minder-data-provider/native`
 */
// #region Types
export type HttpMethod = HttpMethod$1;
// #endregion

// #region Classes
export declare class NativeStorageAdapter extends BaseStorageAdapter {
    private AsyncStorage;
    constructor(_?: StorageAdapterOptions);
    getItem(_: string): Promise<string | null>;
    setItem(_: string, _: string, _?: number): Promise<void>;
    removeItem(_: string): Promise<void>;
    clear(): Promise<void>;
    getAllKeys(): Promise<string[]>;
    hasItem(_: string): Promise<boolean>;
    getSize(): Promise<number>;
    multiGet(_: string[]): Promise<Array<[string, string | null]>>;
    multiSet(_: Array<[string, string]>, _?: number): Promise<void>;
}
// #endregion

// #region Re-exports
export { _ as AnalyticsConfig, _ as AnalyticsPlugin, _ as ApiError, _ as ApiRoute, _ as AuthConfig, _ as CacheConfig, _ as CacheEntry, _ as CacheHitEvent, _ as CacheWarmupPlugin, _ as CorsConfig, _ as CorsHelperConfig, _ as CrudOperations, _ as DebugConfig, _ as EnvironmentOverride, _ as InferInput, _ as InferOutput, _ as LoggerPlugin, _ as MediaUploadResult, _ as MinderConfig, _ as MinderPlugin, _ as Notification, _ as PerformanceConfig, _ as PerformanceMonitorPlugin, _ as PluginError, _ as PluginManager, _ as PluginRequest, _ as PluginResponse, _ as QueryState, _ as RealtimeConfig, _ as RealtimeReconnectConfig, _ as RetryConfig, _ as RetryPlugin, _ as SSRConfig, _ as SecurityConfig, _ as ServerState, _ as SessionData, _ as StandardSchemaV1, _ as TelemetryConfig, _ as UIState, _ as UploadProgress, _ as UserState, _ as WebSocketConfig, _ as createPlugin, _ as pluginManager, _ as registerPlugins } from '../types-HASH.js';
export { _ as AuthManager } from '../AuthManager-HASH.js';
export { _ as CacheManager } from '../CacheManager-HASH.js';
export { configureMinder } from '../config/index.js';
export { _ as CSRFToken, _ as JWTPayload, _ as SecureAuthConfig, _ as SecureAuthManager, _ as TokenRefreshConfig, _ as TokenRefreshManager, _ as UseAuthReturn, _ as createSecureAuthManager, _ as createTokenRefreshManager, _ as useAuth } from '../index-HASH.js';
export { _ as DebugManager } from '../DebugManager-HASH.js';
export { _ as FeatureFlags, _ as FeatureLoader, _ as PlatformCapabilities, _ as PlatformCapabilityDetector, _ as createFeatureLoader } from '../FeatureLoader-HASH.js';
export { _ as FilterOption, _ as PaginationHelper, _ as PaginationOptions, _ as PaginationResult, _ as PaginationState, _ as QueryBuilder, _ as QueryParams, _ as SortOption, _ as query, _ as usePagination, _ as useQueryBuilder } from '../QueryBuilder-HASH.js';
export { MediaUploadManager, UploadOptions, UploadProgressDetails, createUploadManager } from '../upload/index.js';
export { _ as MemoryStorageAdapter, _ as StorageAdapterFactory } from '../MemoryStorageAdapter-HASH.js';
export { _ as minder } from '../minder-HASH.js';
export { _ as MinderDataProvider, _ as useMinder, _ as useMinderContext, _ as useMinderContextSafe } from '../index-HASH.js';
export { _ as MinderError } from '../MinderError-HASH.js';
export { _ as MinderOptions, _ as MinderResult } from '../types-HASH.js';
export { _ as Platform } from '../enums-HASH.js';
export { _ as PlatformDetector } from '../DevTools-HASH.js';
export { _ as PROVIDER_CATEGORIES, _ as PROVIDER_FRAMEWORKS, _ as PROVIDER_RUNTIMES, _ as ProviderCapability, _ as ProviderCategory, _ as ProviderConfigSplit, _ as ProviderDocs, _ as ProviderFramework, _ as ProviderManifest, _ as ProviderRuntime, _ as ProviderScope, _ as ValidationResult, _ as defineProviderManifest, _ as providerManifestSchema, _ as validateProviderManifest } from '../manifest-HASH.js';
export { _ as useAuthToken, _ as useCache, _ as useCurrentUser, _ as useMediaUpload, _ as useWebSocket } from '../index-HASH.js';
export { useDebug } from '../debug/index.js';
export { WebSocketClient, WebSocketEventHandler, WebSocketMessage, WebSocketState, createWebSocketClient } from '../websocket/index.js';
// #endregion