/**
 * Generated by tsnapi — public API snapshot of `minder-data-provider/realtime`
 */
// #region Classes
export declare class SseTransport implements RealtimeTransport {
    private readonly config;
    private readonly authManager;
    private readonly debugManager?;
    private readonly enableLogs;
    private readonly parser;
    private readonly listeners;
    private abortController;
    private stallTimer;
    private reconnectTimer;
    private attempt;
    private epoch;
    private destroyed;
    private connected;
    private pendingConnect;
    private connectPromise;
    constructor(_: ResolvedRealtimeConfig, _: AuthManager, _?: DebugManager, _?: boolean);
    connect(): Promise<void>;
    disconnect(): void;
    subscribe(_: string, _: (_: unknown) => void): () => void;
    isConnected(): boolean;
    send(_: string, _: unknown): void;
    private attemptConnect;
    private readLoop;
    private handleTransientFailure;
    private handlePermanentFailure;
    private giveUp;
    private scheduleReconnect;
    private computeBackoffDelay;
    private markConnected;
    private failInitial;
    private buildHeaders;
    private dispatch;
    private emitClosed;
    private armStallTimer;
    private resetStallTimer;
    private clearStallTimer;
    private clearReconnectTimer;
}
// #endregion

// #region Re-exports
export { _ as RealtimeConfig, _ as RealtimeReconnectConfig } from '../types-HASH.js';
// #endregion

// #region Other
export { RealtimeTransport }
export { ResolvedRealtimeConfig }
// #endregion