/**
 * Generated by tsnapi — public API snapshot of `minder-data-provider/server`
 */
// #region Interfaces
export interface CorsMiddlewareOptions {
    origin?: string | RegExp | Array<string | RegExp>;
    methods?: string[];
    allowedHeaders?: string[];
    credentials?: boolean;
}
export interface WebhookVerifyOptions {
    secret: CredentialInput;
    signatureHeader: string;
    algorithm: 'hmac-sha256';
    timestampToleranceSec?: number;
    timestampHeader?: string;
    payloadFormat?: (_: string, _?: string) => string;
    parseSignatureHeader?: (_: string) => {
        signature: string;
        timestamp?: string;
    } | null;
}
// #endregion

// #region Functions
export declare function createCorsMiddleware(_?: CorsMiddlewareOptions): (_: any, _: any) => Promise<void>;
export declare function createWebhookHandler(_: WebhookVerifyOptions & {
    onEvent: (_: {
        body: unknown;
        rawBody: string;
        headers: Headers;
    }) => Promise<Response | void>;
}): MinderHandler;
export declare function resolveSecret(_: SecretRef | string): string;
export declare function toNodeHandler(_: MinderHandler, _?: MinderHandlerContext): (_: IncomingMessage, _: ServerResponse) => void;
// #endregion

// #region Re-exports
export { _ as describeCredential, _ as env, _ as findExposedSecrets, _ as isCredentialInput, _ as isSecretRef, _ as redactSecrets, _ as resolveCredential, _ as secret } from './credentials-HASH.js';
export { _ as jsonResponse } from './handlers-HASH.js';
// #endregion

// #region Other
export { CredentialInput }
export { MinderHandler }
export { MinderHandlerContext }
export { SecretRef }
// #endregion