/**
 * Generated by tsnapi — public API snapshot of `minder-data-provider/ssr`
 */
// #region Interfaces
export interface SSROptions {
    prefetch?: string[];
    hydrate?: boolean;
    fallback?: any;
}
// #endregion

// #region Functions
export declare function createSSRConfig(_: MinderConfig, _?: SSROptions): {
    ssr: {
        enabled: boolean;
        prefetch: string[];
        hydrate: boolean;
        fallback: any;
    };
    apiBaseUrl: string;
    routes: Record<string, ApiRoute>;
    providers?: Record<string, unknown>;
    dynamic?: (_: () => Promise<any>, _?: {
        ssr?: boolean;
    }) => any;
    auth?: AuthConfig;
    cache?: CacheConfig;
    cors?: CorsConfig;
    corsHelper?: CorsHelperConfig;
    websocket?: WebSocketConfig;
    performance?: PerformanceConfig;
    debug?: DebugConfig;
    security?: SecurityConfig;
    analytics?: AnalyticsConfig;
    telemetry?: TelemetryConfig;
    offline?: OfflineConfig;
    plugins?: MinderPlugin[];
    environments?: Record<string, EnvironmentOverride>;
    defaultEnvironment?: string;
    autoDetectEnvironment?: boolean;
    onError?: (_: ApiError) => void;
    httpClient?: any;
};
export declare function getDehydratedState(_: any, _: Promise<any>[]): Promise<Record<string, any>>;
export declare function prefetchData(_: MinderConfig, _: string[]): Promise<Record<string, unknown>>;
export declare function withCSR(_: string): {
    routeName: string;
    ssr: boolean;
};
export declare function withSSR<T = any>(_: string, _?: T): {
    routeName: string;
    fallback: T | undefined;
    ssr: boolean;
};
// #endregion

// #region Re-exports
export { HydrationBoundary, QueryClient, QueryClientProvider, dehydrate } from '@tanstack/react-query';
// #endregion