/**
 * Generated by tsnapi — public API snapshot of `minder-data-provider/testing`
 */
// #region Interfaces
export interface ContractFailure {
    name: string;
    diff: string;
}
export interface ContractFixture {
    name: string;
    request: ContractRequest;
    expectedResponse: unknown;
}
export interface ContractRequest {
    routeName: string;
    data?: any;
    params?: Record<string, unknown>;
}
export interface ContractTestResult {
    passed: boolean;
    failed: ContractFailure[];
}
export interface MockApiClient {
    request: MockFn<Parameters<ApiClient['request']>, ReturnType<ApiClient['request']>>;
    uploadFile: MockFn<Parameters<ApiClient['uploadFile']>, ReturnType<ApiClient['uploadFile']>>;
    createWebSocket: MockFn<Parameters<ApiClient['createWebSocket']>, ReturnType<ApiClient['createWebSocket']>>;
    getAxiosInstance: MockFn<Parameters<ApiClient['getAxiosInstance']>, ReturnType<ApiClient['getAxiosInstance']>>;
    getPerformanceMetrics: MockFn<Parameters<ApiClient['getPerformanceMetrics']>, ReturnType<ApiClient['getPerformanceMetrics']>>;
    resetPerformanceMetrics: MockFn<Parameters<ApiClient['resetPerformanceMetrics']>, ReturnType<ApiClient['resetPerformanceMetrics']>>;
    destroy: MockFn<Parameters<ApiClient['destroy']>, ReturnType<ApiClient['destroy']>>;
}
export interface MockApiClientOverrides {
    responses?: Record<string, any>;
    axiosInstance?: AxiosInstance;
    performanceMetrics?: ReturnType<ApiClient['getPerformanceMetrics']>;
    implementations?: Partial<{
        request: ApiClient['request'];
        uploadFile: ApiClient['uploadFile'];
        createWebSocket: ApiClient['createWebSocket'];
        getAxiosInstance: ApiClient['getAxiosInstance'];
        getPerformanceMetrics: ApiClient['getPerformanceMetrics'];
        resetPerformanceMetrics: ApiClient['resetPerformanceMetrics'];
        destroy: ApiClient['destroy'];
    }>;
}
export interface MockFn<Args extends any[] = any[], R = any> {
    (..._: Args): R;
    calls: Args[];
    results: R[];
    mockReturnValue(_: R): MockFn<Args, R>;
    mockResolvedValue(_: Awaited<R>): MockFn<Args, R>;
    mockRejectedValue(_: unknown): MockFn<Args, R>;
    mockImplementation(_: (..._: Args) => R): MockFn<Args, R>;
    mockReset(): void;
}
export interface MockProvider {
    manifest: ProviderManifest;
    plugin: MinderPlugin;
}
// #endregion

// #region Types
export type ContractAdapterFn = (_: ContractRequest) => Promise<unknown>;
export type MockProviderImpl = Partial<Pick<MinderPlugin, 'onInit' | 'onRequest' | 'onResponse' | 'onError' | 'onCacheHit' | 'onCacheMiss' | 'onDestroy' | 'provideToken' | 'onAuthRefresh' | 'onUpload' | 'onSync' | 'onConnectivityChange'>>;
// #endregion

// #region Functions
export declare function contractTest(_: ContractAdapterFn, _: ContractFixture[]): Promise<ContractTestResult>;
export declare function createMockFn<Args extends any[] = any[], R = any>(_?: (..._: Args) => R): MockFn<Args, R>;
export declare function createMockProvider(_: ProviderManifest, _?: MockProviderImpl): MockProvider;
export declare function deepEqual(_: unknown, _: unknown): boolean;
export declare function diffValues(_: unknown, _: unknown): string;
export declare function expectNoSecretLeak(_: () => unknown | Promise<unknown>): Promise<void>;
export declare function mockApiClient(_?: MockApiClientOverrides): MockApiClient;
// #endregion