/**
 * Generated by tsnapi — public API snapshot of `minder-data-provider/upload`
 */
// #region Interfaces
export interface UploadOptions {
    onProgress?: (_: UploadProgress) => void;
    resize?: {
        width?: number;
        height?: number;
        fit?: 'cover' | 'contain' | 'fill';
    };
    format?: 'jpeg' | 'png' | 'webp';
    quality?: number;
    endpoint?: string;
    headers?: Record<string, string>;
    chunked?: {
        enabled: boolean;
        chunkSize?: number;
    };
    retry?: {
        attempts?: number;
        delay?: number;
    };
}
export interface UploadProgressDetails {
    loaded: number;
    total: number;
    percentage: number;
    speed?: number;
    estimatedTimeRemaining?: number;
}
// #endregion

// #region Classes
export declare class MediaUploadManager {
    private config;
    private apiClient;
    private debugManager?;
    private activeUploads;
    constructor(_: MinderConfig, _: ApiClient, _?: DebugManager);
    uploadFile(_: File, _?: UploadOptions): Promise<MediaUploadResult>;
    private emitUploadHook;
    uploadImage(_: File, _?: UploadOptions): Promise<MediaUploadResult>;
    uploadMultiple(_: File[], _?: UploadOptions): Promise<MediaUploadResult[]>;
    private uploadDirect;
    private uploadChunked;
    private optimizeImage;
    private uploadWithProgress;
    cancelUpload(_: string): void;
    cancelAll(): void;
    getProgress(_: string): UploadProgress | null;
    getActiveUploads(): Array<{
        id: string;
        file: File;
        progress: UploadProgress;
    }>;
    private generateUploadId;
    private formatBytes;
    private delay;
    private log;
    destroy(): void;
}
// #endregion

// #region Functions
export declare function createUploadManager(_: MinderConfig, _: ApiClient, _?: DebugManager): MediaUploadManager;
// #endregion

// #region Re-exports
export { _ as UploadProgress } from '../types-HASH.js';
export { _ as useMediaUpload } from '../index-HASH.js';
// #endregion

// #region Other
export { MediaUploadResult }
// #endregion