/**
 * Generated by tsnapi — public API snapshot of `minder-data-provider/websocket`
 */
// #region Interfaces
export interface WebSocketEventHandler {
    (_: any): void;
}
export interface WebSocketMessage {
    event: string;
    data: any;
    timestamp?: number;
}
// #endregion

// #region Enums
export declare enum WebSocketState {
    CONNECTING = "CONNECTING",
    CONNECTED = "CONNECTED",
    DISCONNECTING = "DISCONNECTING",
    DISCONNECTED = "DISCONNECTED",
    RECONNECTING = "RECONNECTING",
    ERROR = "ERROR"
}
// #endregion

// #region Classes
export declare class WebSocketClient {
    private config;
    private ws;
    private state;
    private eventHandlers;
    private messageQueue;
    private reconnectAttempts;
    private maxReconnectAttempts;
    private reconnectDelay;
    private heartbeatInterval;
    private reconnectTimeout;
    private debugManager?;
    private lastPingTime;
    private isManualDisconnect;
    constructor(_: WebSocketConfig, _?: DebugManager);
    connect(): Promise<void>;
    disconnect(): void;
    private attemptReconnect;
    send(_: string, _: any): void;
    private handleMessage;
    private processMessageQueue;
    subscribe(_: string, _: WebSocketEventHandler): () => void;
    on(_: string, _: WebSocketEventHandler): () => void;
    unsubscribe(_: string, _: WebSocketEventHandler): void;
    off(_: string, _: WebSocketEventHandler): void;
    private trigger;
    private startHeartbeat;
    private stopHeartbeat;
    getState(): WebSocketState;
    isConnected(): boolean;
    isConnecting(): boolean;
    getQueueSize(): number;
    clearQueue(): void;
    getInfo(): {
        state: WebSocketState;
        url: string;
        connected: boolean;
        queueSize: number;
        reconnectAttempts: number;
    };
    destroy(): void;
    private log;
}
// #endregion

// #region Functions
export declare function createWebSocketClient(_: WebSocketConfig, _?: DebugManager): WebSocketClient;
// #endregion

// #region Re-exports
export { _ as useWebSocket } from '../index-HASH.js';
// #endregion

// #region Other
export { WebSocketConfig }
// #endregion