/**
 * Generated by tsnapi — public API snapshot of `minder-data-provider/providers/authjs`
 */
// #region Interfaces
export interface AuthjsProviderConfig {
    basePath?: string;
    mock?: boolean;
    fetchImpl?: typeof fetch;
}
export interface AuthjsRawSession {
    user?: {
        id?: string;
        email?: string;
        name?: string;
        [key: string]: unknown;
    } | null;
    expires?: string;
    [key: string]: unknown;
}
export interface CreateAuthjsSessionHandlerOptions {
    sessionResolver: (_: Request) => Promise<AuthjsRawSession | null | undefined>;
}
// #endregion

// #region Functions
export declare function createAuthjsSessionHandler(_: CreateAuthjsSessionHandlerOptions): MinderHandler;
export declare function getProviderClient(): unknown;
export declare function registerAuthjsProvider(_?: AuthjsProviderConfig): Promise<() => void>;
// #endregion