/**
 * Generated by tsnapi — public API snapshot of `minder-data-provider/providers/auth0`
 */
// #region Interfaces
export interface Auth0IdTokenClaims {
    sub?: string;
    exp?: number;
    [key: string]: unknown;
}
export interface Auth0ProviderConfig {
    domain?: string;
    clientId?: string;
    audience?: string;
    redirectUri?: string;
    mock?: boolean;
    logoutParams?: Record<string, unknown>;
    createAuth0Factory?: () => unknown;
}
export interface CreateAuth0SessionHandlerOptions {
    domain: string;
}
// #endregion

// #region Functions
export declare function createAuth0SessionHandler(_: CreateAuth0SessionHandlerOptions): MinderHandler;
export declare function getProviderClient(): unknown;
export declare function registerAuth0Provider(_?: Auth0ProviderConfig): Promise<() => void>;
// #endregion