/**
 * Generated by tsnapi — public API snapshot of `minder-data-provider/providers/clerk`
 */
// #region Interfaces
export interface ClerkProviderConfig {
    publishableKey?: string;
    secretKey?: CredentialInput;
    mock?: boolean;
    createClerkFactory?: () => unknown;
}
// #endregion

// #region Functions
export declare function createClerkSessionHandler(_: {
    secretKey: CredentialInput;
    serverConfig?: Record<string, unknown>;
}): MinderHandler;
export declare function getProviderClient(): unknown;
export declare function registerClerkProvider(_?: ClerkProviderConfig): Promise<() => void>;
// #endregion