/**
 * Generated by tsnapi — public API snapshot of `minder-data-provider/providers/cognito`
 */
// #region Interfaces
export interface CognitoIdTokenClaims {
    sub?: string;
    exp?: number;
    [key: string]: unknown;
}
export interface CognitoProviderConfig {
    userPoolId?: string;
    userPoolClientId?: string;
    region?: string;
    mock?: boolean;
    signOutOptions?: {
        global?: boolean;
    };
    createCognitoFactory?: () => unknown;
}
export interface CreateCognitoSessionHandlerOptions {
    userPoolDomain: string;
}
// #endregion

// #region Functions
export declare function createCognitoSessionHandler(_: CreateCognitoSessionHandlerOptions): MinderHandler;
export declare function getProviderClient(): unknown;
export declare function registerCognitoProvider(_?: CognitoProviderConfig): Promise<() => void>;
// #endregion