/**
 * Generated by tsnapi — public API snapshot of `minder-data-provider/providers/firebase`
 */
// #region Interfaces
export interface FirebaseProviderConfig {
    apiKey?: string;
    authDomain?: string;
    projectId?: string;
    storageBucket?: string;
    messagingSenderId?: string;
    appId?: string;
    serviceAccount?: CredentialInput;
    mock?: boolean;
    createFirebaseFactory?: () => unknown;
}
export interface ServiceAccountHealth {
    projectId?: string;
    clientEmail?: string;
    hasPrivateKey: boolean;
}
export interface ValidateServiceAccountResult {
    valid: boolean;
    masked: ServiceAccountHealth;
    errors: string[];
}
// #endregion

// #region Functions
export declare function getProviderClient(): unknown;
export declare function loadServiceAccount(_: CredentialInput): Promise<ValidateServiceAccountResult>;
export declare function registerFirebaseProvider(_?: FirebaseProviderConfig): Promise<() => void>;
export declare function validateServiceAccount(_: unknown): ValidateServiceAccountResult;
// #endregion