/**
 * Generated by tsnapi — public API snapshot of `minder-data-provider/providers/razorpay`
 */
// #region Interfaces
export interface RazorpayProviderConfig {
    keyId?: string;
    keySecret?: CredentialInput;
    webhookSecret?: CredentialInput;
    mock?: boolean;
}
// #endregion

// #region Functions
export declare function createOrderHandler(_: {
    keyId: string;
    keySecret: CredentialInput;
    serverConfig?: Record<string, unknown>;
}): MinderHandler;
export declare function createRazorpayWebhookHandler(_: {
    webhookSecret: CredentialInput;
    onEvent: (_: {
        body: unknown;
        rawBody: string;
        headers: Headers;
    }) => Promise<Response | void>;
}): MinderHandler;
export declare function getProviderClient(): Promise<unknown>;
export declare function registerRazorpayProvider(_?: RazorpayProviderConfig): Promise<() => void>;
// #endregion

// #region Variables
export declare const DEFAULT_ORDER_PATH: string;
// #endregion