/**
 * Generated by tsnapi — public API snapshot of `minder-data-provider/providers/sentry`
 */
// #region Interfaces
export interface SentryLikeClient {
    captureException: (_: unknown) => void;
    captureMessage?: (_: string) => void;
}
export interface SentryProviderConfig {
    dsn?: string;
    mock?: boolean;
    createSentryFactory?: () => SentryLikeClient;
    breadcrumbs?: boolean;
}
// #endregion

// #region Functions
export declare function __resetSentrySdkCache(): void;
export declare function getProviderClient(): Promise<SentryLikeClient | null>;
export declare function registerSentryProvider(_?: SentryProviderConfig): () => void;
// #endregion