/**
 * Generated by tsnapi — public API snapshot of `minder-data-provider/providers/stripe`
 */
// #region Interfaces
export interface StripeProviderConfig {
    publishableKey: string;
    secretKey?: CredentialInput;
    webhookSecret?: CredentialInput;
    checkoutPath?: string;
    mock?: boolean;
}
// #endregion

// #region Functions
export declare function createCheckoutHandler(_: {
    secretKey: CredentialInput;
    serverConfig?: Record<string, unknown>;
}): MinderHandler;
export declare function createStripeWebhookHandler(_: {
    webhookSecret: CredentialInput;
    onEvent: (_: {
        type: string;
        data: unknown;
        raw: unknown;
    }) => Promise<Response | void>;
}): MinderHandler;
export declare function getProviderClient(): Promise<unknown>;
export declare function parseStripeSignatureHeader(_: string): {
    signature: string;
    timestamp?: string;
} | null;
export declare function registerStripeProvider(_?: StripeProviderConfig): Promise<() => void>;
// #endregion

// #region Variables
export declare const DEFAULT_CHECKOUT_PATH: string;
// #endregion