/**
 * Generated by tsnapi — public API snapshot of `minder-data-provider/providers/supabase`
 */
// #region Interfaces
export interface SupabaseProviderConfig {
    url: string;
    anonKey: string;
    serviceRoleKey?: CredentialInput;
    mock?: boolean;
    createClientFactory?: (_: string, _: string) => unknown;
}
// #endregion

// #region Functions
export declare function getProviderClient(): unknown;
export declare function registerSupabaseProvider(_?: SupabaseProviderConfig): Promise<() => void>;
// #endregion