#!/usr/bin/env node

/**
 * Generate docs/providers/CATALOG.md from provider manifests.
 *
 * Scans two roots for manifest.json:
 *   - providers/ (first-party dir; absent today, handled gracefully)
 *   - Any dir passed via --extra flag (tests use fixtures)
 *
 * Validates each minimally (name + displayName + categories present; skip invalid with warning).
 *
 * A CERTIFIED constant array determines the Certified table; others go in Community.
 * A PLANNED constant with 6 providers is rendered in a Planned table.
 *
 * Output docs/providers/CATALOG.md: deterministic (sorted by name), three tables,
 * per-provider columns: displayName, categories, runtimes, frameworks.
 * Footer: "Generated by npm run generate:catalog — do not edit by hand."
 *
 * Usage: node scripts/generate-catalog.js [--extra <dir>] [--out <path>] [--check]
 *   --check   Exit non-zero if the existing output file would change (CI guard).
 *
 * No dependencies beyond Node.js built-ins.
 */

const fs = require('fs');
const path = require('path');

const REPO_ROOT = path.join(__dirname, '..');

// Certified provider names (currently empty; nothing is certified yet)
const CERTIFIED = [];

// Planned providers with roadmap info
const PLANNED = [
  { name: 'Supabase' },
  { name: 'Stripe' },
  { name: 'Clerk' },
  { name: 'Firebase' },
  { name: 'Razorpay' },
  { name: 'Sentry' },
];

/**
 * Find all manifest.json files in a directory tree.
 * Returns an array of { path, dir } objects.
 */
function findManifests(rootDir) {
  const results = [];
  if (!fs.existsSync(rootDir)) return results;

  const walk = (current) => {
    const entries = fs.readdirSync(current, { withFileTypes: true });
    for (const entry of entries) {
      if (entry.name.startsWith('.')) continue;
      const full = path.join(current, entry.name);

      if (entry.isDirectory()) {
        walk(full);
        continue;
      }

      if (entry.name === 'manifest.json') {
        results.push({ path: full, dir: current });
      }
    }
  };

  walk(rootDir);
  return results;
}

/**
 * Minimal validation: check that name, displayName, and categories are present.
 * Returns { valid, errors: [] }.
 */
function validateManifestMinimal(obj, filePath) {
  const errors = [];

  if (!obj || typeof obj !== 'object') {
    errors.push(`${filePath}: Manifest is not a plain object.`);
    return { valid: false, errors };
  }

  if (typeof obj.name !== 'string' || obj.name.trim().length === 0) {
    errors.push(`${filePath}: Missing or empty "name" field.`);
  }

  if (typeof obj.displayName !== 'string' || obj.displayName.trim().length === 0) {
    errors.push(`${filePath}: Missing or empty "displayName" field.`);
  }

  if (!Array.isArray(obj.categories) || obj.categories.length === 0) {
    errors.push(`${filePath}: Missing or empty "categories" array.`);
  }

  return { valid: errors.length === 0, errors };
}

/**
 * Load and minimally validate a manifest file.
 * Returns null if invalid (after logging a warning).
 */
function loadManifest(filePath) {
  try {
    const content = fs.readFileSync(filePath, 'utf8');
    const obj = JSON.parse(content);

    const validation = validateManifestMinimal(obj, filePath);
    if (!validation.valid) {
      for (const err of validation.errors) {
        process.stderr.write(`[generate-catalog] Warning: ${err}\n`);
      }
      return null;
    }

    return obj;
  } catch (err) {
    process.stderr.write(
      `[generate-catalog] Warning: Could not load ${filePath}: ${err.message}\n`
    );
    return null;
  }
}

/**
 * Safely extract fields from a manifest for table rendering.
 */
function extractProviderInfo(manifest) {
  return {
    name: manifest.name || '(unknown)',
    displayName: manifest.displayName || '(unknown)',
    categories: Array.isArray(manifest.categories) ? manifest.categories.join(', ') : '(none)',
    runtimes: Array.isArray(manifest.runtimes) ? manifest.runtimes.join(', ') : '(none)',
    frameworks: Array.isArray(manifest.frameworks) ? manifest.frameworks.join(', ') : '(none)',
  };
}

/**
 * Generate the markdown table for a list of providers.
 * Sorts by displayName for deterministic output.
 */
function generateTable(providers) {
  if (providers.length === 0) {
    return '| displayName | Categories | Runtimes | Frameworks |\n|---|---|---|---|\n| (none) | | | |\n';
  }

  // Sort by displayName for deterministic output
  const sorted = providers.slice().sort((a, b) => a.displayName.localeCompare(b.displayName));

  const lines = ['| displayName | Categories | Runtimes | Frameworks |', '|---|---|---|---|'];
  for (const provider of sorted) {
    lines.push(
      `| ${provider.displayName} | ${provider.categories} | ${provider.runtimes} | ${provider.frameworks} |`
    );
  }

  return lines.join('\n') + '\n';
}

/**
 * Generate the markdown content for the CATALOG.md file.
 */
function generateCatalogContent(certified, community) {
  const header = [
    '# Provider Catalog',
    '',
    '## Overview',
    '',
    'Minder plugins are published providers — integrations with databases, auth, storage, payments, and more. The catalog is organized in three tiers:',
    '',
    '### Certified',
    'Badged providers that have completed the certification process. Each includes a runnable example, comprehensive tests, and meets the 10-point certification checklist. Certified providers are production-ready and supported by the Minder team.',
    '',
    '### Community',
    'Providers that ship the same API as Certified providers and are self-certified by their authors. Community providers are fully functional and follow Minder conventions, but certification is author-driven rather than team-verified.',
    '',
    '### Planned',
    'Providers on the Minder roadmap. These are not yet available — they follow the certification process and may be added as either Certified or Community. No promised dates.',
    '',
  ];

  const sections = [];

  // Certified section
  sections.push('## Certified Providers');
  sections.push('');
  if (certified.length === 0) {
    sections.push('(none yet)');
  } else {
    sections.push(generateTable(certified).trimEnd());
  }
  sections.push('');

  // Community section
  sections.push('## Community Providers');
  sections.push('');
  if (community.length === 0) {
    sections.push('(none yet)');
  } else {
    sections.push(generateTable(community).trimEnd());
  }
  sections.push('');

  // Planned section
  sections.push('## Planned Providers');
  sections.push('');
  sections.push('The following providers are on the Minder roadmap and are not yet available. They follow the certification process.');
  sections.push('');
  const plannedLines = ['| Provider | Status |', '|---|---|'];
  for (const p of PLANNED) {
    plannedLines.push(`| ${p.name} | not yet available — follows the certification process |`);
  }
  sections.push(plannedLines.join('\n'));
  sections.push('');

  // Footer
  const footer = [
    '---',
    '',
    'Generated by `npm run generate:catalog` — do not edit by hand.',
  ];

  return [...header, ...sections, ...footer].join('\n') + '\n';
}

/**
 * Run the generator. Returns { content, certified, community, outputPath, changed }.
 */
function main(options = {}) {
  const providersDir = path.join(REPO_ROOT, 'providers');
  const extraDirs = options.extraDirs || [];
  const outPath = options.outPath || path.join(REPO_ROOT, 'docs', 'providers', 'CATALOG.md');
  const dryRun = Boolean(options.dryRun);

  // Scan manifests
  const allManifests = [];
  const toScan = [providersDir, ...extraDirs];

  for (const dir of toScan) {
    for (const entry of findManifests(dir)) {
      const manifest = loadManifest(entry.path);
      if (manifest) {
        allManifests.push(manifest);
      }
    }
  }

  // Separate into certified and community
  const certifiedSet = new Set(CERTIFIED);
  const certified = [];
  const community = [];

  for (const manifest of allManifests) {
    const info = extractProviderInfo(manifest);
    if (certifiedSet.has(manifest.name)) {
      certified.push(info);
    } else {
      community.push(info);
    }
  }

  // Generate content
  const content = generateCatalogContent(certified, community);

  // Check for changes
  const previous = fs.existsSync(outPath) ? fs.readFileSync(outPath, 'utf8') : null;
  const changed = previous !== content;

  // Write if not dry run
  if (!dryRun) {
    fs.writeFileSync(outPath, content, 'utf8');
  }

  return {
    content,
    certified: certified.length,
    community: community.length,
    outputPath: outPath,
    changed,
  };
}

if (require.main === module) {
  const args = process.argv.slice(2);
  const options = {};
  let checkOnly = false;

  for (let i = 0; i < args.length; i++) {
    if (args[i] === '--extra') {
      const extraPath = path.resolve(args[++i]);
      options.extraDirs = options.extraDirs || [];
      options.extraDirs.push(extraPath);
    } else if (args[i] === '--out') {
      options.outPath = path.resolve(args[++i]);
    } else if (args[i] === '--check') {
      checkOnly = true;
    }
  }

  if (checkOnly) {
    options.dryRun = true;
  }

  const result = main(options);

  if (checkOnly) {
    if (result.changed) {
      process.stderr.write(
        `[generate-catalog] ${path.relative(REPO_ROOT, result.outputPath)} is out of date. ` +
          `Run \`npm run generate:catalog\`.\n`
      );
      process.exit(1);
    }
    process.stdout.write(`[generate-catalog] ${path.relative(REPO_ROOT, result.outputPath)} is up to date.\n`);
    process.exit(0);
  }

  process.stdout.write(
    `[generate-catalog] Wrote ${path.relative(REPO_ROOT, result.outputPath)} ` +
      `with ${result.certified} Certified and ${result.community} Community provider(s).\n`
  );
}

module.exports = {
  main,
  findManifests,
  loadManifest,
  validateManifestMinimal,
  extractProviderInfo,
  generateTable,
  generateCatalogContent,
  CERTIFIED,
  PLANNED,
};
