/**
 * AUTO-GENERATED by `minder generate` — DO NOT EDIT BY HAND.
 * Regenerate with: minder generate --from <openapi.json> --out <this file>
 *
 * Source: tests/fixtures/openapi-petstore.json
 *
 * Path parameters use minder's ":name" URL-template convention (see
 * src/core/ApiClient.ts) — NOT the OpenAPI "{name}" braces.
 */

import type { ApiRoute } from 'minder-data-provider';
import { HttpMethod } from 'minder-data-provider';

export const routes = {
  listPets: { method: HttpMethod.GET, url: "/pets" },
  createPet: { method: HttpMethod.POST, url: "/pets" },
  getPet: { method: HttpMethod.GET, url: "/pets/:petId" },
  updatePet: { method: HttpMethod.PUT, url: "/pets/:petId" },
  deletePet: { method: HttpMethod.DELETE, url: "/pets/:petId" },
  getPetVaccination: { method: HttpMethod.GET, url: "/pets/:petId/vaccinations/:vaccinationId" },
  getPetOwner: { method: HttpMethod.GET, url: "/pets/:petId/owner" },
  getHealth: { method: HttpMethod.GET, url: "/health" },
} as const satisfies Record<string, ApiRoute>;

export type PetStatus = "available" | "pending" | "sold";

export interface Pet {
  id: number;
  name: string;
  tag?: string;
  status: PetStatus;
}

export interface NewPet {
  name: string;
  tag?: string;
}

export interface Vaccination {
  id: number;
  name: string;
  date: string;
}

export interface Person {
  kind: "person";
  name: string;
}

export interface Organization {
  kind: "org";
  name: string;
}

export type ListPetsResponse = Array<Pet>;

export type GetPetOwnerResponse = Person | Organization;

export interface GetHealthResponse {
  status: string;
}

export interface RouteTypes {
  listPets: { response: ListPetsResponse };
  createPet: { body: NewPet; response: Pet };
  getPet: { response: Pet };
  updatePet: { body: NewPet; response: Pet };
  deletePet: {};
  getPetVaccination: { response: Vaccination };
  getPetOwner: { response: GetPetOwnerResponse };
  getHealth: { response: GetHealthResponse };
}
